springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: true
  default-produces-media-type: application/json

spring:
  application:
    name: feature-flag
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 2000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

resilience4j.circuitbreaker.instances.myService:
  registerHealthIndicator: true
  slidingWindowSize: 10
  failureRateThreshold: 10
  waitDurationInOpenState: 5000ms
  permittedNumberOfCallsInHalfOpenState: 3

feature:
  flag:
    service:
      url: http://localhost:8080/

logging:
  level:
    org:
      springframework:
        web: DEBUG

management.endpoints.web.exposure.include: "*"
management.health.livenessstate.enabled: true
management.health.readinessstate.enabled: true
management.endpoint.health.probes.enabled: true

management.endpoint.health.show-details: always
management.info.build.enabled: true
management.info.git.enabled: true