spring:
  application:
    name: feature-flag
  profiles:
    active: ${PROFILE:default}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: true
  default-produces-media-type: application/json

resilience4j.circuitbreaker.instances.myService:
  registerHealthIndicator: true
  slidingWindowSize: 10
  failureRateThreshold: 10
  waitDurationInOpenState: 5000ms
  permittedNumberOfCallsInHalfOpenState: 3

feature:
  flag:
    service:
      url: ${FEATURE_FLAG_SERVICE_URL:http://localhost:8080/}

logging:
  level:
    org:
      springframework:
        web: DEBUG

management.endpoints.web.exposure.include: "*"
management.health.livenessstate.enabled: true
management.health.readinessstate.enabled: true
management.endpoint.health.probes.enabled: true

management.endpoint.health.show-details: always
management.info.build.enabled: true
management.info.git.enabled: true
