spring:
  application:
    name: feature-flag
  datasource:
    url: ${SPRING_DATASOURCE_URL}

    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 2000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

resilience4j.circuitbreaker.instances.myService:
  registerHealthIndicator: true
  slidingWindowSize: 10
  failureRateThreshold: 10
  waitDurationInOpenState: 5000ms
  permittedNumberOfCallsInHalfOpenState: 3

feature:
  flag:
    service:
      url: http://localhost:8080/

logging:
  level:
    org:
      springframework:
        web: TRACE

management.endpoints.web.exposure.include: "*"
management.health.livenessstate.enabled: true
management.health.readinessstate.enabled: true
management.endpoint.health.probes.enabled: true

management.endpoint.health.show-details: always
management.info.build.enabled: true
management.info.git.enabled: true