spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 2000
#      pool-name: HikariCP
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true