apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag
  namespace: default  # Change if you use a custom namespace
spec:
  replicas: 2  # Number of pods to evaluateAllFeatureFlagsOfType
  selector:
    matchLabels:
      app: feature-flag
  template:
    metadata:
      labels:
        app: feature-flag
    spec:
      containers:
        - name: feature-flag
          image: evandrorenan/feature-flag:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: FLAGSDB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: feature-flag-config
                  key: FLAGSDB_CONNECTION_STRING
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: feature-flag-db
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feature-flag-db
                  key: SPRING_DATASOURCE_PASSWORD
