apiVersion: v1
kind: Service
metadata:
  name: feature-flag-service
  namespace: default
spec:
  selector:
    app: feature-flag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP