name: CI/CD Pipeline for feature-flag Microservice

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      feature_flag_sdk_version: ${{ steps.extract_sdk_version.outputs.sdk_version }}
      feature_flag_version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract feature-flag-sdk-springboot version from pom.xml
        id: extract_sdk_version
        run: |
          VERSION=$(grep -A 1 '<artifactId>feature-flag-sdk-springboot</artifactId>' pom.xml | grep -o '<version>[^<]*' | sed 's/<version>//')
          echo "sdk_version=$VERSION" >> $GITHUB_OUTPUT
          echo "FEATURE_FLAG_SDK_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Feature flag SDK version: $VERSION"

      - name: Extract feature-flag version from pom.xml
        id: extract_version
        run: |
          VERSION=$(grep -A 1 '<artifactId>feature-flag</artifactId>' pom.xml | grep -o '<version>[^<]*' | sed 's/<version>//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "FEATURE_FLAG_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Feature flag version: $VERSION"

  prepare_dependencies:
    needs: setup
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache feature-flag-sdk-springboot JAR
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: feature-flag-sdk-springboot-${{ needs.setup.outputs.feature_flag_sdk_version }}-jar-with-dependencies.jar
          key: ${{ runner.os }}-sdk-${{ needs.setup.outputs.feature_flag_sdk_version }}

      - name: Download JAR from GitHub Packages
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          curl -L "https://maven.pkg.github.com/evandrorenan/feature-flag-sdk-springboot/br/com/evandrorenan/feature-flag-sdk-springboot/${{ needs.setup.outputs.feature_flag_sdk_version }}/feature-flag-sdk-springboot-${{ needs.setup.outputs.feature_flag_sdk_version }}-jar-with-dependencies.jar" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o "feature-flag-sdk-springboot-${{ needs.setup.outputs.feature_flag_sdk_version }}-jar-with-dependencies.jar"

      - name: Install JAR to Maven Local Repository
        run: |
          mvn install:install-file -Dfile=feature-flag-sdk-springboot-${{ needs.setup.outputs.feature_flag_sdk_version }}-jar-with-dependencies.jar \
            -DgroupId=br.com.evandrorenan \
            -DartifactId=feature-flag-sdk-springboot \
            -Dversion=${{ needs.setup.outputs.feature_flag_sdk_version }} \
            -Dpackaging=jar

  build:
    needs: [setup, prepare_dependencies]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and compile with Maven
        run: mvn clean install -DskipTests=true

  test:
    needs: [setup, build]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with JUnit
        run: mvn test
        # Note: Uncommented the test step that was commented in the original file

  package:
    needs: [setup, test]
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Dockerfile
        run: |
          sed -i "s/__VERSION__/${{ needs.setup.outputs.feature_flag_version }}/g" Dockerfile

      - name: Clean up Docker configuration
        run: |
          rm -rf ~/.docker
          mkdir -p ~/.docker
          echo '{ "auths": { "https://index.docker.io/v1/": {} } }' > ~/.docker/config.json

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feature-flag:${{ needs.setup.outputs.feature_flag_version }} .

  publish:
    needs: [setup, package]
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/feature-flag:${{ needs.setup.outputs.feature_flag_version }}

  deploy:
    needs: [setup, publish]
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup KUBECONFIG
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl config use-context kind-web3270

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/feature-flag feature-flag=${{ secrets.DOCKER_USERNAME }}/feature-flag:${{ needs.setup.outputs.feature_flag_version }} --record
          kubectl rollout status deployment/feature-flag

  cleanup:
    needs: [setup]
    runs-on: self-hosted
    if: always()

    steps:
      - name: Remove local Docker images
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          docker image prune -f

      - name: Clean workspace
        run: |
          rm -f kubeconfig.yaml
          docker logout